spring.mvc:
  pathmatch:
      matching-strategy: ant_path_matcher
spring.jpa:
  properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:55000/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres