spring.mvc:
  pathmatch:
      matching-strategy: ant_path_matcher
spring.jpa:
  properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
